### ISSUE TITLE
dataset download link not working

### ISSUE THREAD

**Issue by KulikovNA** [hughw19/NOCS#64]
Good afternoon, thank you for your work, I would very much like to conduct training, but today the link to the datasets does not work(
Maybe you saved the datasets on google drive or know some other workaround?
I also tried downloading as recommended in https://github.com/hughw19/NOCS_CVPR2019/issues/59

**Comment by drsrinathsridhar** [comment]
https://www.sfchronicle.com/bayarea/article/Stanford-campus-goes-dark-after-power-failure-17256593.php

**Comment by KulikovNA** [comment]
@drsrinathsridhar , thank you for the information, I didn't know, I hope everything will be back to normal soon
