### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Saafke** [hughw19/NOCS#67]
Hi,

Thanks for this great work! What is the license for this repository? If you could add it, that would be greatly appreciated. Thanks in advance.

FYI - [here's](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) what happens if a repository has no license:
"You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work."

Best,
Saafke

**Comment by hughw19** [comment]
An MIT license is added.



Best,
He

**Comment by Saafke** [comment]
Thanks!
