### ISSUE TITLE
Unable to download data 

### ISSUE THREAD

**Issue by andrewyguo** [hughw19/NOCS#73]
I am unable to download data via the link http://download.cs.stanford.edu/orion/nocs/camera_train.zip

![image](https://github.com/hughw19/NOCS_CVPR2019/assets/54864799/a242fb85-f169-4178-abb8-1f57c056efe7)

**Comment by KerwenX** [comment]
Hi @andrewyguo 
I have encountered the same problem. Have you found the solution?

**Comment by Deamerrong123** [comment]
Actually, you cannot download the dataset directly from browser. It gonna be using command-line `curl -O $url`. And, also the training data set is so large; it might take a few hours to download it.
