### ISSUE TITLE
cannot download the datasets

### ISSUE THREAD

**Issue by CAN-Lee** [hughw19/NOCS#81]
I cannot download any datasets you mentioned. Dose someone meet the problem? THANKS
kantleecan@gmail.com

**Comment by francis-j-k** [comment]
Hello,
I am unable to download the dataset too. Could you pls provide resources to get the dataset from? Thanks

**Comment by drsrinathsridhar** [comment]
The links on the main github README all seem to work for me. FWIW, `wget` seemed to work better than trying to download via web browser.
